### ISSUE TITLE
Add Kali Source?

### ISSUE THREAD

**Issue by JiangXL** [SUSTC/MirrorsSync#1]
Hi, is it possible to add **kali** source? 👍 Thanks.

**Comment by lightsing** [comment]
Accepted

**Comment by lightsing** [comment]
Waiting for first time sync complete.

**Comment by JiangXL** [comment]
However, no **Kali** is found in source list now : )

**Comment by lightsing** [comment]
Pls wait patiently.
Beta <notifications@github.com>于2017年5月1日 周一21:28写道：

**Comment by lightsing** [comment]
There it is. [kali mirror](https://mirrors.sustc.us/kali/)
Enjoy yourself. :)
