### ISSUE TITLE
Err: "403  Forbidden" and help file of web don't exist

### ISSUE THREAD

**Issue by JiangXL** [SUSTC/MirrorsSync#2]
* http://mirrors.sustc.us/kali kali-rolling/main amd64 libc6-dbg amd64 2.24-10
  403  Forbidden
* http://mirrors.sustc.us/help don't work

**Comment by lightsing** [comment]
Waiting for sync complete.

**Comment by JiangXL** [comment]
How long time is...

**Comment by lightsing** [comment]
Is the problem still exist?

**Comment by JiangXL** [comment]
Yes, some files still can not download. But here is less files which are 403 forbidden. 
So, it will take more time to sync complete?

**Comment by lightsing** [comment]
Please list the files that cannot be accessed below. We will check it later.

**Comment by JiangXL** [comment]
It just is the problem of my conf.
Now, it run. So I close this issue.
